config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :contact_requests, path: 'contact-requests', only: %i(new create)

    member do
      put :sold, to: 'articles#mark_as_sold'
    end
  end
  resources :contact_requests, path: 'contact-requests', only: %i(index show destroy)
  resources :subscribers, path: 'subscribers', only: %i(create)

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  scope :active_storage, module: :active_storage, as: :active_storage do
    resources :attachments, only: [:destroy]
  end

  root to: redirect('/articles')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many_attached :images
  has_many :contact_requests, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :price_range, numericality: true, allow_blank: true

  def main_image
    @main_image ||= images.order(id: :asc).first
  end

  def sold?
    sold_at.present?
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/contact_request.rb
class ContactRequest < ApplicationRecord
  belongs_to :article

  validates :name, presence: true
  validates :email, presence: true, format: /.+@.+\..+/
  validates :phone, presence: true, phone: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/active_storage/attachments_controller.rb
class ActiveStorage::AttachmentsController < ApplicationController
  def destroy
    @attachment = ActiveStorage::Attachment.find(params[:id])
    @record = @attachment.record
    authorize @record

    @attachment.purge_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  include Pundit
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  helper_method :current_user
  helper_method :logged_in?

  rescue_from 'Pundit::NotAuthorizedError' do
    redirect_to root_path
  end

  def set_locale
    I18n.locale = 'de-CH'
  end

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :mark_as_sold]

  # GET /articles
  def index
    @articles = policy_scope(Article).where(sold_at: nil).includes(:images_blobs, :contact_requests).order(id: :desc)
    @articles = @articles.where(category_id: params[:category_id]) if params[:category_id]
    authorize @articles

    respond_to do |format|
      format.html
      format.rss do
        render layout: false
      end
    end
  end

  # GET /articles/1
  def show
    authorize @article
  end

  # GET /articles/new
  def new
    @article = Article.new
    authorize @article
  end

  # GET /articles/1/edit
  def edit
    authorize @article
  end

  # POST /articles
  def create
    @article = Article.new(article_params)
    authorize @article

    if @article.save
      @article.images.attach(params[:article][:images]) if params[:article][:images]

      redirect_to @article, notice: {
        title: 'Artikel erstellt',
        text: 'Artikel wurde erfolgreich erstellt',
      }
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    authorize @article

    @article.images.attach(params[:article][:images]) if params[:article][:images]

    if @article.update(article_params)
      redirect_to @article, notice: {
        title: 'Änderungen gespeichert',
        text: 'Die Änderungen am Artikel wurden erfolgreich gespeichert',
      }
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    authorize @article
    @article.destroy

    redirect_to articles_url, notice: {
      title: 'Artikel gelöscht',
      text: 'Der Artikel wurde gelöscht',
    }
  end

  def mark_as_sold
    authorize @article
    @article.update! sold_at: Time.zone.now

    redirect_to articles_url, notice: {
      title: 'Artikel verkauft',
      text: 'Der Artikel wurde als verkauft markiert',
    }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :price_range, :category_id)
    end
end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  before_action :set_article, only: [:new, :create]

  def index
    @contact_requests = policy_scope(ContactRequest).includes(:article).order(id: :desc)
    authorize @contact_requests
  end

  def show
  end

  def new
    @contact_request = @article.contact_requests.new
    authorize @contact_request
  end

  def create
    @contact_request = @article.contact_requests.new(contact_request_params)
    authorize @contact_request

    if @contact_request.save
      ContactRequestMailer.created(@contact_request).deliver_later
      redirect_to @article, notice: {
        title: 'Anfrage versandt',
        text: 'Vielen Dank für deine Anfrage! Wir werden uns demnächst bei Dir melden.',
      }
    else
      render :new
    end
  end

  def destroy
    @contact_request = ContactRequest.find(params[:id])
    authorize @contact_request
    @contact_request.destroy

    redirect_to contact_requests_url, notice: {
      title: 'Anfrage gelöscht',
      text: 'Die Anfrage wurde gelöscht',
    }
  end

  private
    def set_article
      @article = Article.find(params[:article_id])
    end

    def contact_request_params
      params.require(:contact_request).permit(:contact_request_id, :name, :email, :phone, :price, :message)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_after_action :verify_authorized

  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/articles'
    else
      redirect_to '/login'
    end
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  skip_after_action :verify_authorized

  def create
    gibbon = Gibbon::Request.new
    if email = params[:subscriber][:email].presence
      email = email.downcase
      email_hash = Digest::MD5.hexdigest(email)
      Gibbon::Request.lists(ENV['MAILCHIMP_LIST_ID']).members(email_hash).upsert(body: { email_address: email, status: 'subscribed' })
      interests = Gibbon::Request.lists(ENV['MAILCHIMP_LIST_ID']).members(email_hash).retrieve(params: { fields: 'interests' }).body['interests']
      interests[ENV['MAILCHIMP_INTEREST_ID']] = true
      Gibbon::Request.lists(ENV['MAILCHIMP_LIST_ID']).members(email_hash).update(body: { interests: interests })
      session[:subscribed] = true
    else
      head :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/active_storage/attachments/destroy.js.erb
document.getElementById("<%= dom_id @attachment %>").remove()

app/views/application/_flash.html.erb
<% if notice %>
  <article class="message is-success">
    <div class="message-header">
      <p><%= notice['title'] %></p>
    </div>
    <div class="message-body">
      <%= notice['text'] %>
    </div>
  </article>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, 'Titel', class: 'label' %>
    <div class="control">
      <%= form.text_field :title, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :category, 'Kategorie', class: 'label' %>
    <div class="control">
      <div class="select">
        <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :name, @article.category_id) %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :price_range, 'Preisrahmen', class: 'label' %>
    <div class="control">
      <%= form.text_field :price_range, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, 'Beschreibung', class: 'label' %>
    <div class="control">
      <div class="wysiwyg"></div>
      <%= form.hidden_field :description, class: 'wysiwyg-target' %>
    </div>
  </div>


  <div class="field">
    <div class="columns">
      <div class="column is-full">
        <div class="label">Bilder</div>
      </div>
    </div>

    <div class="columns">
      <div class="column is-full">
        <div class="file has-name">
          <label class="file-label">
            <%= form.file_field :images, multiple: true, class: 'file-input' %>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fas fa-upload"></i>
              </span>
              <span class="file-label">
                Choose a file...
              </span>
            </span>
            <span class="file-name">
              No file uploaded
            </span>
          </label>
        </div>
      </div>
    </div>

    <div class="columns">
      <% @article.images.each do |image| %>
        <div class="column" id="<%= dom_id(image) %>">
          <div class="card">
            <% if image.representable? %>
              <div class="card-image">
                <figure class="image is-3by2">
                  <%= image_tag image.representation(resize_to_limit: [700, 700]) %>
                </figure>
              </div>
            <% end %>
            <footer class="card-footer">
              <%= link_to(
                'Löschen',
                active_storage_attachment_path(image),
                method: :delete,
                remote: :true,
                class: 'card-footer-item',
                data: { confirm: 'Bist du sicher?' },
              )
            %>
            </footer>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-success' %>
  </div>
<% end %>

<script>
  const fileInput = document.querySelector('.file input[type=file]');
  fileInput.onchange = () => {
    if (fileInput.files.length > 0) {
      const fileName = document.querySelector('.file .file-name');

      if (fileInput.files.length === 1) {
        fileName.textContent = fileInput.files[0].name;
      } else {
        fileName.textContent = 'Multiple';
      }
    }
  }
</script>

app/views/articles/edit.html.erb
<section class="section">
  <div class="container is-max-desktop">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><%= link_to 'Alle Artikel', articles_path %></li>
        <li class="is-active"><%= link_to 'Artikel Editieren', edit_article_path(@article), 'aria-current' => 'page' %></li>
      </ul>
    </nav>

    <h1 class="title"><%= @article.title %> editieren</h1>

    <%= render 'form', article: @article %>
  </div>
</section>

app/views/articles/index.html.erb
<section class="section">
  <div class="container is-max-desktop">
    <h1 class="title">Online Flohmi</h1>
    <div class="content">
      <p>Hallo<p>
      <p>Willkommen in unserem Online Flohmi. Schön schaust Du vorbei!</p>
      <p>Wir lösen einen grossen Teil unserers Haushalts auf, daher möchten wir vieles <strong>weitergeben</strong> oder <strong>verkaufen</strong>.</p>
      <p>
        Gefällt Dir etwas? Dann reservier dir diesen Artikel. Wir werden darauf hin mit Dir Kontakt aufnehmen um alles Weitere zu besprechen (Preis, Übergabe, ...).<br />
        Überleg Dir doch was Dir der Gegenstand wert ist. Unsere Preise sehen wir als Verhandlungsbasis.<br />
      </p>
      <p>Fühl dich frei uns auch für Artikel zu kontaktieren welche bereits Interessenten haben.</p>
      <p>Frohes Stöbern! Bei Fragen oder Unklarheiten einfach melden.</p>
      <p>Liebe Grüsse</p>
      <p>Familie Schmid</p>

      <% unless session[:subscribed] %>
        <div id="js-subscriber-form">
          <p>PS: Wenn du über neue Artikel informiert werden möchtest, kannst du uns hier deine E-Mail Adresse hinterlassen.</p>
          <%= form_for :subscriber, url: subscribers_path, remote: true do |form| %>
            <div class="field has-addons">
              <div class="control">
                <%= form.email_field :email, required: true, placeholder: 'benutzer@example.org', class: 'input' %>
              </div>
              <div class="control">
                <%= form.submit 'Infos Abonnieren', class: 'button is-info' %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
</section>
<section class="section">
  <div class="container is-max-desktop">
    <div class="tabs">
      <ul>
        <li class="<%= params[:category_id].blank? ? 'is-active' : '' %>"><%= link_to 'Alle', articles_path %></li>
        <% Category.order(position: :asc).each do |category| %>
          <li class="<%= params[:category_id].to_i == category.id ? 'is-active' : '' %>"><%= link_to category.name, articles_path(category_id: category.id) %></li>
        <% end %>
      </ul>
    </div>
    <% @articles.in_groups_of(3, false) do |articles| %>
      <div class="columns">
        <% articles.each do |article| %>
          <div class="column">
            <div class="card">
              <% if article.main_image %>
                <div class="card-image">
                  <figure class="image is-350x350">
                    <%= image_tag article.main_image.representation(resize_to_fill: [700, 700]) %>
                  </figure>
                  <div class="card-image-stamp">
                    <% if article.contact_requests.present? %>
                      <div class="tag is-medium is-info is-light">
                        Hat Interessenten
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
              <div class="card-content">
                <p class="is-size-5">
                  <%= article.title %>
                </p>
                <p class="block is-size-6">
                  <% if article.price_range %>
                    Um <%= number_to_currency article.price_range, unit: 'CHF' %>
                  <% else %>
                    Keine Preisvorstellung
                  <% end %>
                </p>
                <p class="block is-size-6 is-italic has-text-grey-light">Am <%= l(article.created_at.to_date) %> hinzugefügt</p>
              </div>
              <footer class="card-footer">
                <%= link_to 'Anzeigen', article, class: 'card-footer-item' %>
                <% if policy(article).edit? %>
                  <%= link_to 'Anpassen', edit_article_path(article), class: 'card-footer-item' %>
                <% end %>
              </footer>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/articles/new.html.erb
<section class="section">
  <div class="container is-max-desktop">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><%= link_to 'Alle Artikel', articles_path %></li>
        <li class="is-active"><%= link_to 'Neuer Artikel', new_article_path, 'aria-current' => 'page' %></li>
      </ul>
    </nav>

    <h1 class="title">Neuen Artikel erstellen</h1>

    <%= render 'form', article: @article %>
  </div>
</section>

app/views/articles/show.html.erb
<section class="section">
  <div class="container is-max-desktop">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><%= link_to 'Alle Artikel', articles_path %></li>
        <li class="is-active"><%= link_to @article.title, article_path(@article), 'aria-current' => 'page' %></li>
      </ul>
    </nav>

    <h1 class="title"><%= @article.title %></h1>

    <%= render 'flash' %>

    <div class="columns">
      <div class="column is-8">
        <% if @article.images.length == 1 %>
          <%= image_tag @article.images.first.representation(resize_to_fit: [2000,2000]) %>
        <% else %>
          <div class="gallery block">
            <div class="gallery__navigation">
              <% @article.images.each do |image| %>
                <%= image_tag image.representation(resize_to_limit: [300, 250]), class: 'gallery__preview-image', data: { 'full-version' => url_for(image.representation(resize_to_limit: [2000,2000])) } %>
              <% end %>
            </div>
            <div class="gallery__zoomed-image"></div>
          </div>
        <% end %>
      </div>

      <div class="column is-4">
        <div class="mb-6">
          <h2 class="is-size-4">Beschreibung</h2>
          <div class="content"><%= sanitize @article.description %></div>
        </div>
        <div class="block">
          <h2 class="is-size-4">Interessiert?</h2>
          <div class="mb-1">
            <% if @article.price_range %>
              <span class="is-italic">Unsere Preisvorstellung:</span>
              <%= number_to_currency @article.price_range, unit: 'CHF' %>
            <% else %>
              <span class="is-italic">
                Wir haben keine Preisvorstellung
              </span>
            <% end %>
          </div>
          <%= link_to 'Anfragen', new_article_contact_request_path(@article), remote: true, class: 'button is-primary' %>
        </div>
        <% if policy(@article).edit? || policy(@article).destroy? %>
          <div class="block">
            <% if policy(@article).edit? %>
              <%= link_to 'Ändern', edit_article_path(@article), class: 'button is-link is-small' %>
            <% end %>
            <% if policy(@article).mark_as_sold? %>
              <%= link_to 'Verkauft!', sold_article_path(@article), class: 'button is-pimrary is-light is-small', method: :put %>
            <% end %>
            <% if policy(@article).destroy? %>
              <%= link_to 'Löschen', article_path(@article), class: 'button is-danger is-light is-small', method: :delete, data: { confirm: 'Bist du sicher?' } %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/contact_requests/_new.html.erb
<%= simple_form_for(@contact_request, url: article_contact_requests_path, remote: true) do |form| %>
  <div class="modal is-active">
    <div class="modal-background"></div>

    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title">Interessiert an <%= @article.title %>?</p>
        <a class="delete" aria-label="close"></a>
      </header>

      <section class="modal-card-body">
        <%= form.input :name, label: 'Dein Name' %>
        <%= form.input :email, label: 'Email' %>
        <%= form.input :phone, label: 'Telefon' %>
        <%= form.input :price, label: 'Betrag (CHF)' %>
        <%= form.input :message, label: 'Deine Nachricht' %>
      </section>

      <footer class="modal-card-foot">
        <%= form.submit 'Anfrage absenden', class: 'button is-success' %>
        <button class="button form-cancel">Abbrechen</button>
      </footer>
    </div>
  </div>
<% end %>

app/views/contact_requests/index.html.erb
<section class="section">
  <div class="container is-max-desktop">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Artikel</th>
          <th>Preis</th>
          <th>Email</th>
          <th>Telefon</th>
          <th>Nachricht</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @contact_requests.each do |contact_request| %>
          <tr>
            <td><%= contact_request.name %></td>
            <td><%= link_to contact_request.article.title, article_path(contact_request.article) %></td>
            <td><%= number_to_currency contact_request.price, unit: 'CHF' %></td>
            <td><%= link_to contact_request.email, "mailto:#{contact_request.email}" %></td>
            <td><%= link_to contact_request.phone, "tel:#{contact_request.phone}" %></td>
            <td>
            <%= truncate contact_request.message, length: 15, omission: '...' do %>
              <div class="modal">
                <div class="modal-background"></div>
                <div class="modal-content">
                  <div class="box content">
                    <%= simple_format contact_request.message %>
                  </div>
                </div>
                <button class="modal-close is-large" aria-label="close"></button>
              </div>
              <button class="button is-text is-small modal-trigger">[Mehr]</button>
            <% end %>
            </td>
            <td><%= button_to 'Löschen', contact_request_path(contact_request), method: :delete, class: 'button is-danger is-small' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/contact_requests/new.js.erb
(() => {
  const remoteContainer = document.querySelector('#js-remote-content');
  remoteContainer.innerHTML = "<%= j(render('new')) %>";
})();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flohmi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= auto_discovery_link_tag :rss, articles_url(format: :rss) %>
  </head>

  <body>
    <div id="js-remote-content"></div>

    <% if logged_in? %>
      <div class="container is-max-desktop">
        <nav class="navbar" role="navigation" aria-label="main navigation">
          <div class="navbar-brand">
            <% if policy(Article).index? %>
              <%= link_to 'Artikel', articles_path, class: 'navbar-item' %>
            <% end %>
            <% if policy(Article).new? %>
              <%= link_to 'Neuen Artikel hinzufügen', new_article_path, class: 'navbar-item' %>
            <% end %>
            <% if policy(ContactRequest).index? %>
              <%= link_to 'Anfragen', contact_requests_path, class: 'navbar-item' %>
            <% end %>
          </div>
        </nav>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/subscribers/_create.html.erb
<article class="message is-success">
  <div class="message-header">
    <p>Erfolgreich abonniert!</p>
  </div>
  <div class="message-body">
    Vielen Dank für dein Interesse! Du wirst von nun an informiert wenn neue Artikel aufgeschaltet werden.
  </div>
</article>

app/views/subscribers/create.js.erb
(() => {
  const subscriberForm = document.querySelector('#js-subscriber-form');
  subscriberForm.innerHTML = "<%= j(render('create')) %>";
})();